spring.application.name=T1-FeignGrupo12

clients.json-placeholder.url=${JSON_PLACEHOLDER_URL:https://jsonplaceholder.typicode.com}
clients.github.url=${GITHUB_API_URL:https://api.github.com}
clients.fake-store.url=${FAKE_STORE_API_URL:https://fakestoreapi.com}


spring.cloud.openfeign.client.config.albumClient.connectTimeout=5000
spring.cloud.openfeign.client.config.albumClient.readTimeout=10000
spring.cloud.openfeign.client.config.albumClient.loggerLevel=basic
spring.cloud.openfeign.client.config.githubEventClient.connectTimeout=5000
spring.cloud.openfeign.client.config.githubEventClient.readTimeout=10000
spring.cloud.openfeign.client.config.githubEventClient.loggerLevel=basic
spring.cloud.openfeign.client.config.fakeUserClient.connectTimeout=5000
spring.cloud.openfeign.client.config.fakeUserClient.readTimeout=10000
spring.cloud.openfeign.client.config.fakeUserClient.loggerLevel=basic

logging.level.pe.edu.cibertec.t1feigngrupo1.client.AlbumClient=DEBUG
logging.level.pe.edu.cibertec.t1feigngrupo1.client.GithubEventClient=DEBUG
logging.level.pe.edu.cibertec.t1feigngrupo1.client.FakeUserClient=DEBUG
